### `OS` 모듈

#### `os.path.join`
- 여러 경로 결합하여 하나의 경로 반환

In [2]:
import os

path = os.path.join("folder", "subfolder", "file.txt")
print(path)

folder\subfolder\file.txt


#### `os.path.dirname`
- 파일 경로에서 디렉토리 경로 반환

In [3]:
directory = os.path.dirname("/path/to/file.txt")
print(directory)

/path/to


#### `os.path.abspath`
- 현재 작업 디렉토리 기준으로 절대 경로 반환

In [4]:
abs_path = os.path.abspath("file.txt")
print(abs_path)

c:\Users\82105\Documents\dev\TIL\ml\file.txt


### `dict`

#### `dict` + `zip`
- 두 리스트를 병합하여 딕셔너리 생성

In [5]:
keys = ['a', 'b', 'c']
values = [1, 2, 3]

result = dict(zip(keys, values))
print(result)

{'a': 1, 'b': 2, 'c': 3}


#### `dict` + `enumerate`
- 리스트의 각 항목에 인덱스 매핑

In [6]:
items = ['apple', 'banana', 'cherry']

result = dict(enumerate(items))
print(result)

{0: 'apple', 1: 'banana', 2: 'cherry'}


### `LabelEncoder`

#### `transform`
- 학습된 라벨 정보를 사용하여 데이터를 숫자로 변환 ex) 범주형 데이터 정수형 변환

In [7]:
from sklearn.preprocessing import LabelEncoder

categories = ['dog', 'cat', 'bird']
encoder = LabelEncoder()
encoder.fit(categories)

encoded = encoder.transform(['dog', 'bird'])
print(encoded)

[2 0]


#### `fit_transform`
- 데이터를 학습하고 즉시 변환 (라벨 인코딩 한 번에 수행)

In [8]:
encoded = encoder.fit_transform(categories)
print(encoded)

[2 1 0]


### `StandardScaler`

#### `transform`
- 데이터를 학습된 평균과 표준편차를 사용하여 변환 (데이터 스케일링)

In [9]:
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([[1.0, 2.0], [2.0, 4.0], [3.0, 6.0]])
scaler = StandardScaler()
scaler.fit(data)

scaled = scaler.transform(data)
print(scaled)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


#### `fit_transform`
- 데이터를 학습하고 즉시 변환

In [11]:
scaled = scaler.fit_transform(data)
print(scaled)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


### `@property`
- 메서드를 속성처럼 호출할 수 있도록 하는 데코레이터

In [12]:
class Example:
    def __init__(self, value):
        self._value = value
    
    @property
    def value(self):
        return self._value
    
obj = Example(42)
print(obj.value)

42


### 특수 메서드

#### `__len__`
- 객체의 길이를 반환하는 메서드

In [13]:
class MyList:
    def __init__(self, items):
        self.items = items

    def __len__(self):
        return len(self.items)
    
obj = MyList([1, 2, 3])
print(len(obj))

3


#### `__getitem__`
- 객체에서 특정 인덱스의 값을 반환하슨 메서드

In [14]:
class MyList:
    def __init__(self, items):
        self.items = items
    
    def __getitem__(self, idx):
        return self.items[idx]
    
obj = MyList([1, 2, 3])
print(obj[1])

2
